# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Nestoria-Search
version:      0.04
version_from: lib/WebService/Nestoria/Search.pm
installdirs:  site
requires:
    Carp:                          0
    HTTP::Request:                 0
    JSON:                          0
    LWP::UserAgent:                0
    Module::Build:                 0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
