--- #YAML:1.0
name:                WebService-Nestoria-Search
version:             0.12
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    HTTP::Request:                 0
    JSON:                          0
    LWP::UserAgent:                0
    Module::Build:                 0
    Test::More:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
