---
name: WebService-Nestoria-Search
version: 0.01
author:
  - Alex Balhatchet (kaoru@slackwise.net)
abstract: Perl interface to the Nestoria Search public API.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  URI: 0
build_requires:
  Module::Build: 0
  Test::More: 0
provides:
  WebService::Nestoria::Search:
    file: lib/WebService/Nestoria/Search.pm
    version: 0.01
  WebService::Nestoria::Search::Request:
    file: lib/WebService/Nestoria/Search/Request.pm
  WebService::Nestoria::Search::Response:
    file: lib/WebService/Nestoria/Search/Response.pm
  WebService::Nestoria::Search::Result:
    file: lib/WebService/Nestoria/Search/Result.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
