--- #YAML:1.0
name:                WebService-Nestoria-Search
version:             1.14.7
abstract:            WebService::Nestoria::Search provides a Perl interface to the public API of Nestoria, a vertical search engine for property listings. Nestoria currently has listings for the UK, Germany, Italy and Spain, which can be accessed via the web at www.nestoria.co.uk, www.nestoria.de, www.nestoria.co.it and www.nestoria.es.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    HTTP::Request:                 0
    JSON:                          2
    LWP::UserAgent:                0
    Module::Build:                 0
    Test::More:                    0
    URI:                           0
    version:                       0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alex Balhatchet (kaoru at slackwise dot net), Yoav Felberbaum (perl at mrdini dot com), Alistair Francis (cpan at alizta dot com)
