---
abstract: 'Perl interface to the Nestoria Search public API'
author:
  - 'Alex Balhatchet (kaoru at slackwise dot net), Yoav Felberbaum (perl at mrdini dot com), Alistair Francis (cpan at alizta dot com)'
build_requires:
  List::MoreUtils: 0
  Module::Build: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Nestoria-Search
provides:
  WebService::Nestoria::Search:
    file: lib/WebService/Nestoria/Search.pm
    version: v1.17.4
  WebService::Nestoria::Search::MetadataResponse:
    file: lib/WebService/Nestoria/Search/MetadataResponse.pm
  WebService::Nestoria::Search::Request:
    file: lib/WebService/Nestoria/Search/Request.pm
  WebService::Nestoria::Search::Response:
    file: lib/WebService/Nestoria/Search/Response.pm
  WebService::Nestoria::Search::Result:
    file: lib/WebService/Nestoria/Search/Result.pm
requires:
  Carp: 0
  HTTP::Request: 0
  JSON: 2
  LWP::UserAgent: 0
  URI: 0
  XML::Simple: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v1.17.4
